
STATE_DISCONNECTED = 0
STATE_CONNECTING = 1
STATE_WEBSOCKET_CONNECTED = 3
STATE_AUTHENTICATING = 4
STATE_CONNECTED = 2

REGISTERED_CALL_URI = 0
REGISTERED_CALL_CALLBACK = 1
SUBSCRIPTION_TOPIC = 0
SUBSCRIPTION_CALLBACK = 1

SERIALIZERS = ['json','msgpack','cbor','ubjson','flatbuffers']
SERIALIZERS_BLACKLIST = ['ubjson','flatbuffers']
SERIALIZER_REGISTRY = {}

WEBSOCKET_SERIALIZER_JSON = 'wamp.2.json'
WEBSOCKET_SERIALIZER_MESSAGEPACK = 'wamp.2.msgpack'
WEBSOCKET_SERIALIZER_CBOR = 'wamp.2.cbor'
WEBSOCKET_SERIALIZER_UBJSON = 'wamp.2.ubjson'
WEBSOCKET_SERIALIZER_FLATBUFFERS = 'wamp.2.flatbuffers'

RAWSOCKET_SERIALIZER_JSON = 1
RAWSOCKET_SERIALIZER_MESSAGEPACK = 1
RAWSOCKET_SERIALIZER_CBOR = 2
RAWSOCKET_SERIALIZER_UBJSON = 3
RAWSOCKET_SERIALIZER_FLATBUFFERS = 4

RAWSOCKET_HANDSHAKE_ERRORS = {
    0: 'illegal (must not be used)',
    1: 'serializer unsupported',
    2: 'maximum message length unacceptable',
    3: 'use of reserved bits (unsupported feature)',
    4: 'maximum connection count reached',
}

RAWSOCKET_MESSAGE_TYPE_REGULAR = 0
RAWSOCKET_MESSAGE_TYPE_PING = 1
RAWSOCKET_MESSAGE_TYPE_PONG = 2
